services:
  subextract:
    build: .
    environment:
      TZ: America/Sao_Paulo
      #List with subtitles to extract. ex: [eng, por, spa]. If empty it will extract all subtitles
      SUBTITLES_TO_EXTRACT: "[]"
      #Check if subtitle file already exists to avoid redundant extraction. Default "eng"
      DEFAULT_SUB: "eng"
    restart: unless-stopped
    container_name: subextract
    volumes:
      - /location/of/videos:/app/subextract/videos:rw
