services:
  subextract:
    build: .
    environment:
      TZ: America/Sao_Paulo
    restart: unless-stopped
    container_name: subextract
    volumes:
      - /location/of/videos:/app/subextract/videos:rw
